name: Create Pull Request

on:
  push:
    branches-ignore:
      - '*'

jobs:
  create_pull_request:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          title: "Pull Request"
          body: " - triggered"
